volumes:
  postgres:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .docker.env
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    command: make run
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 4s
      timeout: 5s
      start_period: 1s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      start_period: 1s
      retries: 5
